"$schema" = "https://starship.rs/config-schema.json"
format = "$directory$git_branch$git_status$cmd_duration$line_break$character"
add_newline = false

[directory]
truncation_length = 3
truncate_to_repo = true

[git_branch]
symbol = "git:"

[character]
success_symbol = "[>](bold green)"
error_symbol = "[>](bold red)"
